target(
    dependencies = [
        "scrooge/scrooge-adaptive/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    dependencies = [
        "scrooge/scrooge-adaptive/src/test/scala",
    ],
)
