java_thrift_library(
    name = "include-scala",
    sources = ["include3.thrift"],
    compiler = "scrooge",
    language = "scala",
    platform = "java8",
    tags = ["bazel-compatible"],
)

resources(
    name = "resources",
    sources = ["**/*"],
    tags = ["bazel-compatible"],
)
