junit_tests(
    sources = ["com/twitter/example/DemoTest.scala"],
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/scalatest",
        "3rdparty/jvm/org/scalatestplus:junit",
        "scrooge/demos/scrooge-maven-demo/src/main/scala",
        "scrooge/demos/scrooge-maven-demo/src/main/thrift",
        "util/util-core:scala",
    ],
)
