junit_tests(
  dependencies=[
    '3rdparty/jvm/junit',
    '3rdparty/jvm/org/scalatest',
    'scrooge/demos/scrooge-maven-demo/src/main/scala',
  ],
  sources=globs('com/twitter/example/DemoSpec.scala'),
)