java_thrift_library(
    name = "thrift-android",
    sources = ["*.thrift"],
    compiler = "scrooge",
    language = "android",
    tags = ["bazel-compatible"],
)

resources(
    name = "resources",
    sources = ["*.thrift"],
    tags = ["bazel-compatible"],
)
