--[[
  Generated by Scrooge
    version: ?
    rev: ?
    built at: ?
--]]

-- Import this file with:
--   require 'com.twitter.scrooge.test.gold.thriftlua.AnotherException'
-- Note: This file depends on libthrift!



local AnotherException = {
  ttype = 'struct',
  name = 'AnotherException',
  fields = { }
}

AnotherException.fields[1] = { name = 'errorCode', required = true, ttype = 'i32', }

local binaryCodec = require 'libthrift'

AnotherException.__codec = binaryCodec.codec(AnotherException)

function AnotherException:read(bin)
  return self.__codec:read(bin)
end

function AnotherException:readTensor(bin)
  return self.__codec:readTensor(bin)
end

function AnotherException:write(params)
  return self.__codec:write(params)
end

function AnotherException:writeTensor(params)
  return self.__codec:writeTensor(params)
end

return AnotherException
