--[[
  Generated by Scrooge
    version: ?
    rev: ?
    built at: ?
    source file: scrooge/scrooge-generator-tests/src/test/resources/gold_file_input/gold.thrift
--]]

-- Import this file with:
--   require 'com.twitter.scrooge.test.gold.thriftlua.OverCapacityException'
-- Note: This file depends on libthrift!



local OverCapacityException = {
  ttype = 'struct',
  name = 'OverCapacityException',
  fields = { }
}

OverCapacityException.fields[1] = { name = 'chillTimeSeconds', required = true, ttype = 'i32', }

local binaryCodec = require 'libthrift'

OverCapacityException.__codec = binaryCodec.codec(OverCapacityException)

function OverCapacityException:read(bin)
  return self.__codec:read(bin)
end

function OverCapacityException:readTensor(bin)
  return self.__codec:readTensor(bin)
end

function OverCapacityException:write(params)
  return self.__codec:write(params)
end

function OverCapacityException:writeTensor(params)
  return self.__codec:writeTensor(params)
end

return OverCapacityException
