package com.twitter.example

import org.specs.SpecificationWithJUnit
import org.apache.thrift.protocol.TBinaryProtocol
import org.apache.thrift.transport.TMemoryBuffer

class FooSpec extends SpecificationWithJUnit {
  val protocol = new TBinaryProtocol(new TMemoryBuffer(10000))
  "test code" should {
    import mythrift.week._
    import mythrift.bird_renamed._
    "work with scala code generated by maven-scrooge plugin" in {
      Constants.myWfhDay mustEqual(WeekDay.Thu)

      val originalPenguin = Bird(canFly = false, habitat = "Antarctica")
      Bird.encode(originalPenguin, protocol)
      Bird.decode(protocol) mustEqual(originalPenguin)
    }
  }
}

