scala_library(
    name = "scala",
    sources = ["com/twitter/example/Demo.scala"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "scrooge/demos/scrooge-maven-demo/src/main/thrift",
        "scrooge/scrooge-core",
    ],
)
