scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "scrooge/scrooge-adaptive",
        "scrooge/scrooge-serializer/src/main/scala",
        "util/util-codec/src/main/scala",
    ],
)
