scala_library(
  dependencies=[
    'scrooge/scrooge-adaptive',
    'scrooge/scrooge-serializer/src/main/scala:scala',
    'util/util-codec/src/main/scala:scala',
  ],
  fatal_warnings=True,
  sources=globs('*.scala'),
)


