scala_library(
    sources = globs("*.scala"),
    compiler_option_sets = {"fatal_warnings"},
    dependencies = [
        "scrooge/scrooge-adaptive",
        "scrooge/scrooge-serializer/src/main/scala",
        "util/util-codec/src/main/scala",
    ],
)
