/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: eb527853cd68a47db6989d5d8ad99cf9fd1e2a1b
 *   built at: 20170322-114458
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'

import {TalonResponse} from './TalonResponse'

export class TalonResponseException {
    public response: TalonResponse
    public message: string
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            input.skip(ftype)
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("TalonResponseException")
        if (this.response !== null && this.response !== undefined) {
            // writing response
            if (this.response !== null) {
                const response_item = this.response
                output.writeFieldBegin("response", Thrift.Type.STRUCT, 1)
                // isList: false, isSet: false, isMap: false, isStruct: ?, isEnum: false, isBase: false
                response_item.write(output)
                output.writeFieldEnd()
            }
        }
        if (this.message !== null && this.message !== undefined) {
            // writing message
            if (this.message !== null) {
                const message_item = this.message
                output.writeFieldBegin("message", Thrift.Type.STRING, 2)
                // isList: false, isSet: false, isMap: false, isStruct: false, isEnum: false, isBase: ?
                output.writeString(message_item)
                output.writeFieldEnd()
            }
        }
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}