/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: 37381b506e4da989e44d86ebf4c7f8eb1e08ca2e
 *   built at: 20170322-170703
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'

import {TalonResponse} from './TalonResponse'

export class TalonResponseException {
    public response: TalonResponse
    public message: string
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            switch (fid) {
                case 1:
                    // reading response
                    this.response = (() => {
                                        const struct = new TalonResponse()
                                        struct.read(input)
                                        return struct
                                    })()
                    break
case 2:
                    // reading message
                    this.message = input.readString()
                    break

                default:
                    input.skip(ftype)
            }
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("TalonResponseException")
        if (this.response !== null && this.response !== undefined) {
            // writing response
            if (this.response !== null) {
                const response_item = this.response
                output.writeFieldBegin("response", Thrift.Type.STRUCT, 1)
                response_item.write(output)
                output.writeFieldEnd()
            }
        }
        if (this.message !== null && this.message !== undefined) {
            // writing message
            if (this.message !== null) {
                const message_item = this.message
                output.writeFieldBegin("message", Thrift.Type.STRING, 2)
                output.writeString(message_item)
                output.writeFieldEnd()
            }
        }
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}