scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    provides = scala_artifact(
        org = "com.twitter",
        name = "scrooge-core-thrift_validation",
        repo = artifactory,
    ),
    tags = ["bazel-compatible"],
)
