resources(
    sources = [
        "!**/*.pyc",
        "!BUILD*",
        #"!test_thrift/**/*",
        "!gold_file_output_*/**/*",
        "!test_thrift/swift/swift.thrift",
        "!gold_file_input/gold.thrift",
        "!test_thrift/cocoa.thrift",
        "**/*",
    ],
    tags = ["bazel-compatible"],
)

files(
    name = "files",
    sources = [
        "!**/*.pyc",
        "!BUILD*",
        "**/*",
    ],
)
