#!/bin/bash

args=("$@")
cp=${args[0]}
out=${args[1]}

javaNamespace="-n thrift.test=thrift.java_test
-n thrift.test1=thrift.java_test1
-n thrift.test2=thrift.java_test2
-n thrift.def.default=thrift.java_def.default"

javaRun="java -cp $cp com.twitter.scrooge.Main --verbose --finagle --ostrich -d $out -l java $javaNamespace"
scalaRun="java -cp $cp com.twitter.scrooge.Main --verbose --finagle --ostrich -d $out -l scala"

echo "compiling all thrift files except those in relative/"
standalone_thrifts=`find src/test/thrift -name *.thrift | grep -v src/test/thrift/relative`
$javaRun $standalone_thrifts
$scalaRun $standalone_thrifts

echo "compiling dependency of relative/candy.thrift"
dependency_thrifts=`find src/test/thrift/ -name "*include*.thrift"`
$javaRun $dependency_thrifts
$scalaRun $dependency_thrifts

echo "compiling relative/candy.thrift"
importArg="-i src/test/thrift/relative/dir2:src/test/thrift/relative/include3.jar"
$javaRun $importArg src/test/thrift/relative/candy.thrift
$scalaRun $importArg src/test/thrift/relative/candy.thrift

echo "compiling airport example and generating vanilla code"
airport_thrifts=`find src/test/thrift/airport -name *.thrift`
vanillaNamespace="-n thrift.test=vanilla.test
-n thrift.test1=vanilla.test1
-n thrift.test2=vanilla.test2"

javaVanillaNamespace="-n thrift.test=vanilla_java.test
-n thrift.test1=vanilla_java.test1
-n thrift.test2=vanilla_java.test2"

scalaVanillaRun="java -cp $cp com.twitter.scrooge.Main --verbose -d $out -l scala $vanillaNamespace"
javaVanillaRun="java -cp $cp com.twitter.scrooge.Main --verbose -d $out -l java $javaVanillaNamespace"
$scalaVanillaRun $airport_thrifts
$javaVanillaRun $airport_thrifts