#!/bin/bash

args=("$@")
cp=${args[0]}
out=${args[1]}
manifestDir=$out/manifests

javaNamespace="-n thrift.test=thrift.java_test
-n thrift.test1=thrift.java_test1
-n thrift.test2=thrift.java_test2
-n thrift.def.default=thrift.java_def.default"

javaRun="java -cp $cp com.twitter.scrooge.Main --verbose --finagle --ostrich -d $out -l java $javaNamespace"
scalaRun="java -cp $cp com.twitter.scrooge.Main --verbose --finagle --ostrich -d $out -l scala"

echo "compiling standalone thrift files"
standalone_thrifts=`find src/test/thrift/*.thrift`
$javaRun $standalone_thrifts
$scalaRun $standalone_thrifts

echo "compiling dependency of candy.thrift"
dependency_thrifts=`find src/test/thrift/ -name "*include*.thrift"`
$javaRun $dependency_thrifts
$scalaRun $dependency_thrifts

echo "compiling candy.thrift"
importArg="-i src/test/thrift/relative/dir2:src/test/thrift/relative/include3.jar"
$javaRun $importArg src/test/thrift/relative/candy.thrift
$scalaRun $importArg src/test/thrift/relative/candy.thrift

