junit_tests(
    sources = rglobs("*.scala"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/apache/thrift:libthrift",
        "3rdparty/jvm/org/scalatest",
        "scrooge/scrooge-core/src/main/scala",
        "scrooge/scrooge-serializer",
        "scrooge/scrooge-serializer/src/test/thrift:thrift-scala",
        "util/util-app/src/main/scala",
    ],
)
