/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: b5540a5ea44ab683c536210956fb2e7c3497b122
 *   built at: 20170330-131250
 */


export enum AnnotationType {

    Bool,

    Bytes,

    I16,

    I32,

    I64,

    Double,

    String,
}