/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: 37381b506e4da989e44d86ebf4c7f8eb1e08ca2e
 *   built at: 20170322-170720
 */
/**
 * Binary annotations are tags applied to a Span to give it context. For
 * example, a binary annotation of "http.uri" could the path to a resource in a
 * RPC call.
 *
 * Binary annotations of type STRING are always queryable, though more a
 * historical implementation detail than a structural concern.
 *
 * Binary annotations can repeat, and vary on the host. Similar to Annotation,
 * the host indicates who logged the event. This allows you to tell the
 * difference between the client and server side of the same key. For example,
 * the key "http.uri" might be different on the client and server side due to
 * rewriting, like "/api/v1/myresource" vs "/myresource. Via the host field,
 * you can see the different points of view, which often help in debugging.
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'

import {AnnotationType} from './AnnotationType'
import {Endpoint} from './Endpoint'

export class BinaryAnnotation {
    public key: string
    public value: Buffer
    public annotationType: thrift.AnnotationType
    public host: Endpoint
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            switch (fid) {
                case 1:
                    // reading key
                    this.key = input.readString()
                    break
case 2:
                    // reading value
                    this.value = input.readBinary()
                    break
case 3:
                    // reading annotationType
                    this.annotationType = input.readI32()
                    break
case 4:
                    // reading host
                    this.host = (() => {
                                        const struct = new Endpoint()
                                        struct.read(input)
                                        return struct
                                    })()
                    break

                default:
                    input.skip(ftype)
            }
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("BinaryAnnotation")
        if (this.key !== null && this.key !== undefined) {
            // writing key
            if (this.key !== null) {
                const key_item = this.key
                output.writeFieldBegin("key", Thrift.Type.STRING, 1)
                output.writeString(key_item)
                output.writeFieldEnd()
            }
        }
        if (this.value !== null && this.value !== undefined) {
            // writing value
            if (this.value !== null) {
                const value_item = this.value
                output.writeFieldBegin("value", Thrift.Type.STRING, 2)
                output.writeBinary(value_item)
                output.writeFieldEnd()
            }
        }
        if (this.annotationType !== null && this.annotationType !== undefined) {
            // writing annotationType
            if (this.annotationType !== null) {
                const annotationType_item = this.annotationType
                output.writeFieldBegin("annotationType", Thrift.Type.ENUMI32, 3)
                output.writeI32(annotationType_item)
                output.writeFieldEnd()
            }
        }
        if (this.host !== null && this.host !== undefined) {
            // writing host
            if (this.host !== undefined) {
                const host_item = this.host
                output.writeFieldBegin("host", Thrift.Type.STRUCT, 4)
                host_item.write(output)
                output.writeFieldEnd()
            }
        }
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}