/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: eb527853cd68a47db6989d5d8ad99cf9fd1e2a1b
 *   built at: 20170322-114513
 */
/**
 * These are connection-level options negotiated during protocol
 * upgrade.
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'



export class ConnectionOptions {
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            input.skip(ftype)
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("ConnectionOptions")
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}