/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: eb527853cd68a47db6989d5d8ad99cf9fd1e2a1b
 *   built at: 20170322-114513
 */
/**
 * Serializes an individual delegation.
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'



export class Delegation {
    public src: string
    public dst: string
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            input.skip(ftype)
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("Delegation")
        if (this.src !== null && this.src !== undefined) {
            // writing src
            if (this.src !== null) {
                const src_item = this.src
                output.writeFieldBegin("src", Thrift.Type.STRING, 1)
                // isList: false, isSet: false, isMap: false, isStruct: false, isEnum: false, isBase: ?
                output.writeString(src_item)
                output.writeFieldEnd()
            }
        }
        if (this.dst !== null && this.dst !== undefined) {
            // writing dst
            if (this.dst !== null) {
                const dst_item = this.dst
                output.writeFieldBegin("dst", Thrift.Type.STRING, 2)
                // isList: false, isSet: false, isMap: false, isStruct: false, isEnum: false, isBase: ?
                output.writeString(dst_item)
                output.writeFieldEnd()
            }
        }
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}