/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: 37381b506e4da989e44d86ebf4c7f8eb1e08ca2e
 *   built at: 20170322-170720
 */
/**
 * Indicates the network context of a service recording an annotation with two
 * exceptions.
 *
 * When a BinaryAnnotation, and key is CLIENT_ADDR or SERVER_ADDR,
 * the endpoint indicates the source or destination of an RPC. This exception
 * allows zipkin to display network context of uninstrumented services, or
 * clients such as web browsers.
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'



export class Endpoint {
    public ipv4: number
    public port: number
    public serviceName: string
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            switch (fid) {
                case 1:
                    // reading ipv4
                    this.ipv4 = input.readI32()
                    break
case 2:
                    // reading port
                    this.port = input.readI16()
                    break
case 3:
                    // reading serviceName
                    this.serviceName = input.readString()
                    break

                default:
                    input.skip(ftype)
            }
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("Endpoint")
        if (this.ipv4 !== null && this.ipv4 !== undefined) {
            // writing ipv4
            if (true) {
                const ipv4_item = this.ipv4
                output.writeFieldBegin("ipv4", Thrift.Type.I32, 1)
                output.writeI32(ipv4_item)
                output.writeFieldEnd()
            }
        }
        if (this.port !== null && this.port !== undefined) {
            // writing port
            if (true) {
                const port_item = this.port
                output.writeFieldBegin("port", Thrift.Type.I16, 2)
                output.writeI16(port_item)
                output.writeFieldEnd()
            }
        }
        if (this.serviceName !== null && this.serviceName !== undefined) {
            // writing serviceName
            if (this.serviceName !== null) {
                const serviceName_item = this.serviceName
                output.writeFieldBegin("serviceName", Thrift.Type.STRING, 3)
                output.writeString(serviceName_item)
                output.writeFieldEnd()
            }
        }
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}