/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: 37381b506e4da989e44d86ebf4c7f8eb1e08ca2e
 *   built at: 20170322-170720
 */
/**
 * This is the struct that a successful upgrade will reply with.
 */


import thrift from 'thrift'
import {Q, Thrift} from 'thrift'



export class UpgradeReply {
    constructor(args?) {
    }

    public read(input) {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            switch (fid) {
                
                default:
                    input.skip(ftype)
            }
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output) {
        output.writeStructBegin("UpgradeReply")
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}