/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: b5540a5ea44ab683c536210956fb2e7c3497b122
 *   built at: 20170330-131250
 */
/**
 * This is the struct that a successful upgrade will reply with.
 */


import thrift from 'thrift'
import {Thrift, Protocol} from 'thrift'




export class UpgradeReply {
    constructor(args?: {}) {
    }

    public read(input: Protocol): void {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            input.skip(ftype)
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output: Protocol): void {
        output.writeStructBegin("UpgradeReply")
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}