java_thrift_library(
    name = "include-scala",
    sources = ["include2.thrift"],
    compiler = "scrooge",
    language = "scala",
    tags = ["bazel-compatible"],
)

resources(
    name = "resources",
    sources = ["**/*"],
)
