/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 */


@import ApacheThrift.TBase;

@interface TFNTwitterThriftScribeTestStruct : NSObject <TBase, NSCoding>

@property (nonatomic, copy) NSString * name;
@property (nonatomic, readonly) BOOL nameIsSet;

@property (nonatomic, copy) NSSet * values;
@property (nonatomic, readonly) BOOL valuesIsSet;

@property (nonatomic) int32_t price;
@property (nonatomic, readonly) BOOL priceIsSet;


- (instancetype)initWithName:(NSString *)name values:(NSSet *)values price:(int32_t)price;
- (void)read:(id<TProtocol>)inProtocol;
- (void)write:(id<TProtocol>)outProtocol;

@end
