/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 *   source file: scrooge/scrooge-generator-tests/src/test/resources/test_thrift/cocoa.thrift
 */
#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, TFNTwitterThriftScribeTestEnum) {
  TFNTwitterThriftScribeTestEnum_FIELD_ONE = 1,
  TFNTwitterThriftScribeTestEnum_FIELD_TWO = 2
};
