/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 *   source file: scrooge/scrooge-generator-tests/src/test/resources/test_thrift/cocoa.thrift
 */
#import "TFNTwitterThriftScribeTestEmptyStruct.h"

@import ApacheThrift;

@implementation TFNTwitterThriftScribeTestEmptyStruct

- (NSString*)description
{
    NSMutableString* ms = [NSMutableString stringWithString:@"TFNTwitterThriftScribeTestEmptyStruct( "];
    [ms appendString:@")"];
    return [NSString stringWithString:ms];
}

- (instancetype)initWithCoder:(NSCoder*)decoder
{
    if (self = [super init]) {
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder*)encoder
{
}


- (void)read:(id <TProtocol>)inProtocol
{
    NSString* fieldName;
    int fieldType;
    int fieldID;

    [inProtocol readStructBeginReturningName:nil];
    while (true) {
        [inProtocol readFieldBeginReturningName:&fieldName type:&fieldType fieldID:&fieldID];
        if (fieldType == TType_STOP) {
            break;
        }
        switch (fieldID) {
        default:
            NSLog(@"%s: unexpected field ID %i with type %i.  Skipping.", __PRETTY_FUNCTION__, fieldID, fieldType);
            [TProtocolUtil skipType:fieldType onProtocol:inProtocol];
            break;
        }
        [inProtocol readFieldEnd];
    }
    [inProtocol readStructEnd];
    [self validate];
}

- (void)write:(id <TProtocol>)outProtocol
{
    [self validate];
    [outProtocol writeStructBeginWithName:@"TFNTwitterThriftScribeTestEmptyStruct"];
    [outProtocol writeFieldStop];
    [outProtocol writeStructEnd];
}

- (void)validate
{
}

@end
