create_thrift_libraries(
  base_name='thrift',
  sources=globs('*.thrift'),
  generate_languages=["java", "scala"],
  provides_java_name='scrooge-serializer-test-thrift-java',
  provides_scala_name='scrooge-serializer-test-thrift-scala',
)
