create_thrift_libraries(
  base_name='thrift',
  sources=globs('*.thrift'),
  jvm_only=True,
  provides_java_name='scrooge-serializer-test-thrift-java',
  provides_scala_name='scrooge-serializer-test-thrift-scala',
)
