junit_tests(
    sources = rglobs("*.scala"),
    fatal_warnings = True,
    dependencies = [
        "3rdparty/jvm/junit",
        "3rdparty/jvm/org/apache/thrift:libthrift-0.5.0",
        "3rdparty/jvm/org/scalacheck",
        "3rdparty/jvm/org/scalatest",
        "finagle/finagle-core",
        "finagle/finagle-thrift/src/main/scala",
        "scrooge/scrooge-adaptive",
        "scrooge/scrooge-adaptive/src/test/scala/com/twitter/scrooge/adapt/testutil",
        "scrooge/scrooge-adaptive/src/test/thrift:thrift-scala",
        "scrooge/scrooge-core/src/main/scala",
        "scrooge/scrooge-serializer",
        "util/util-codec/src/main/scala",
    ],
)
