target(
    tags = ["bazel-compatible"],
    dependencies = [
        "scrooge/scrooge-core/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    tags = ["bazel-compatible"],
    dependencies = [
        "scrooge/scrooge-core/src/test/scala",
    ],
)
