//
// Automatically @generated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Foundation
import TwitterApacheThrift
@objc(TESTSubobjectThriftStruct)
@objcMembers
public class SubobjectThriftStruct: NSObject, ThriftCodable {
    public var value: ThriftStruct?
    public var intValue: Int16
    enum CodingKeys: Int, CodingKey {
        case value = 1
        case intValue = 2
    }
    public init(value: ThriftStruct? = nil, intValue: Int16) {
        self.value = value
        self.intValue = intValue
        super.init()
    }
    public override var hash: Int {
        var hasher = Hasher()
        hasher.combine(self.value)
        hasher.combine(self.intValue)
        return hasher.finalize()
    }
    public override func isEqual(_ object: Any?) -> Bool {
        guard let other = object as? Self else {
            return false
        }
        return self.value == other.value &&
        self.intValue == other.intValue
    }
}
