//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Foundation
import TwitterApacheThrift
@objc(TESTThriftStruct)
@objcMembers
public class ThriftStruct: NSObject, ThriftCodable {
    public var int16Value: Int16?
    enum CodingKeys: Int, CodingKey {
        case int16Value = 1
    }
    public init(int16Value: Int16? = nil) {
        self.int16Value = int16Value
        super.init()
    }
    public override var hash: Int {
        var hasher = Hasher()
        hasher.combine(self.int16Value)
        return hasher.finalize()
    }
    public override func isEqual(_ object: Any?) -> Bool {
        guard let other = object as? Self else {
            return false
        }
        return self.int16Value == other.int16Value
    }
}
