//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Foundation
import TwitterApacheThrift
@objc(TESTUnionClassB)
@objcMembers
public class UnionClassB: NSObject, ThriftCodable {
    public var someInt: Int64
    enum CodingKeys: Int, CodingKey {
        case someInt = 1
    }
    public init(someInt: Int64) {
        self.someInt = someInt
        super.init()
    }
    public override var hash: Int {
        var hasher = Hasher()
        hasher.combine(self.someInt)
        return hasher.finalize()
    }
    public override func isEqual(_ object: Any?) -> Bool {
        guard let other = object as? Self else {
            return false
        }
        return self.someInt == other.someInt
    }
}
