/**
 * Generated by Scrooge
 *   version: 4.13.0-SNAPSHOT
 *   rev: b5540a5ea44ab683c536210956fb2e7c3497b122
 *   built at: 20170330-131242
 */
/**
 * It's considered good form to declare an exception type for your service.
 * Thrift will serialize and transmit them transparently.
 */


import thrift from 'thrift'
import {Thrift, Protocol} from 'thrift'



export interface ITodoExceptionArgs {
    description: string
}

export class TodoException {
    public description: string
    constructor(args: ITodoExceptionArgs) {
            if (args.description != null) {
                this.description = args.description
            } else {
                throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field description is unset!')
            }
    }

    public read(input: Protocol): void {
        input.readStructBegin()
        while (true) {
            const {fname, ftype, fid} = input.readFieldBegin()
            if (ftype === Thrift.Type.STOP) {
                break
            }
            switch (fid) {
                case 1:
                    this.description = input.readString()
                    break
                default:
                    input.skip(ftype)
            }
            input.readFieldEnd()
        }
        input.readStructEnd()
        return
    }

    public write(output: Protocol): void {
        output.writeStructBegin("TodoException")
        if (this.description != null) {
            if (this.description !== null) {
                const description_item = this.description
                output.writeFieldBegin("description", Thrift.Type.STRING, 1)
                output.writeString(description_item)
                output.writeFieldEnd()
            }
        }
        output.writeFieldStop()
        output.writeStructEnd()
        return
    }
}