/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 */


@import ApacheThrift.TBase;

@interface TFNTwitterThriftGoldCollectionId : NSObject <TBase, NSCoding>

@property (nonatomic) int64_t collectionLongId;
@property (nonatomic, readonly) BOOL collectionLongIdIsSet;


- (instancetype)initWithCollectionLongId:(int64_t)collectionLongId;
- (void)read:(id<TProtocol>)inProtocol;
- (void)write:(id<TProtocol>)outProtocol;

@end
