/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 */


@import ApacheThrift.TBase;

@interface TFNTwitterThriftGoldRequestUnion : NSObject <TBase, NSCoding>

@property (nonatomic) int32_t id_;
@property (nonatomic, readonly) BOOL id_IsSet;

@property (nonatomic, copy) NSString * name;
@property (nonatomic, readonly) BOOL nameIsSet;


- (instancetype)initWithId_:(int32_t)id_;
- (instancetype)initWithName:(NSString *)name;
- (void)read:(id<TProtocol>)inProtocol;
- (void)write:(id<TProtocol>)outProtocol;

@end
