{{#isList}}
_iprot.offsetSkipList()
{{/isList}}
{{#isSet}}
_iprot.offsetSkipSet()
{{/isSet}}
{{#isMap}}
_iprot.offsetSkipMap()
{{/isMap}}
{{#isStruct}}
_iprot.offsetSkipStruct()
{{/isStruct}}
{{#isEnum}}
_iprot.offsetSkipEnum()
{{/isEnum}}
{{#isBase}}
_iprot.{{protocolSkipMethod}}()
{{/isBase}}
