target(
    dependencies = [
        "scrooge/scrooge-serializer/src/main/scala",
    ],
)

target(
    name = "tests",
    dependencies = [
        "scrooge/scrooge-serializer/src/test/scala",
    ],
)
