target(
    tags = ["bazel-compatible"],
    dependencies = [
        "scrooge/scrooge-serializer/src/main/scala",
    ],
)

test_suite(
    name = "tests",
    tags = ["bazel-compatible"],
    dependencies = [
        "scrooge/scrooge-serializer/src/test/scala",
    ],
)
