//
// Autogenerated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


enum Constants {
    static let i64_i64_map: [Int64:Int64] = [1 : 1, 2147483648 : 2147483648, -2147483649 : -2147483649]

    static let i64_set: Set<Int64> = [1, 2147483648, -2147483649]

    static let i64_list: [Int64] = [1, 2147483648, -2147483649]

    static let constWithRHS: StructWithMap = StructWithMap(data: ["a" : 1, "b" : 2], emptylist: [])

}
