//
// Automatically @generated by Scrooge
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Foundation
import TwitterApacheThrift
struct UnionStruct: Hashable {
    var someUnion: MyUnion
    enum CodingKeys: Int, CodingKey {
        case someUnion = 1
    }
    init(someUnion: MyUnion) {
        self.someUnion = someUnion
    }
}
extension UnionStruct: ThriftCodable {}
